### PR TITLE
Overhaul for snippets site

### PR DESCRIPTION
**Pull request by antfu**
I will start working on overhauling the snippets site on branch `dev`. This PR is for progressing tacking.

You can preview it on https://deploy-preview-1--wenyan-snippets.netlify.com/

- The code name placeholder `文言片語`, if you got a better idea, feel free to edit it.
- If you don't mind, I will use [Vue.js](https://vuejs.org) for better components isolation and maintainability.
- I will work on the functionality first and the DB migration later

I have made some styling changes for now. Would love to hear what you think about it too.

### CODE REVIEW

**Comment by LingDong-** [comment]
Sounds great. I like the new nav bar! 

One tiny little thing, on mac Chrome, when you continue scrolling up when already at top, there's a "springy" thing that allows you to see extra strip of blankness

image

I think Chrome is mostly to blame (Safari works fine), but if you could perhaps make the body background light gray and 'content' div white, or, perhaps add some gray padding to top of nav div, we could mitigate the problem. (just being nitpicky here :)

> If you don't mind, I will use Vue.js for better components isolation and maintainability.

Feel free to introduce technologies if you see fit! I'm not familiar with vue, but I'm happy to learn it.

**Comment by antfu** [comment]
I have changed the background color to match the navbar color, the white margin is gone but now the problem comes to the bottom 😇

Not sure how to take a screenshot while scrolling, but you can check out the live preview by scrolling to the bottom. (surprise to see even Github have that white margin XP

**Comment by LingDong-** [comment]
> the problem comes to the bottom

Yeah, and while the top looks good on Chrome, it becomes weird on Safari instead:

image

> add some gray padding to top of nav div

Would this hack work? Don't worry too much about it though, or maybe just forget it, even Github doesn't care XD

**Comment by antfu** [comment]
Emmm... My Safari acts the same as Chrome but it doesn't care about the html background.

> add some gray padding to top of nav div

No luck with that. Anything out of the viewport will not get rendered :(

Should I keep the grey or change back to white?

**Comment by LingDong-** [comment]
Let's go back to white. So sorry for all this trouble!

**Comment by antfu** [comment]
Some progress FYI,

- The website is rewriting in Vue.js
- The editor is working in progress
- I have added some new APIs that aim to be more flexible. You can check out the quick docs https://github.com/wenyan-lang/snippets/tree/dev
- Made the voting limited to once per IP address, and you can see your voting state and even cancel that
- Made a pagination system with 10 snippets per page, will auto load on scrolling as we discussed before

The Glitch access in China is still not ideal, it takes unacceptable long time to load a single page. And still, no problem through a proxy. :(

**Comment by antfu** [comment]
It's almost done! The remain things are some stability tests and some polish. But before I that, I would like to hear what you think about it. Please check the preview when you got some time :)

Notable Changes
- Username and token are now global. (token will be assigned to a random string on the first visit) You can choose to publish the snippet to the public domain or use your own token (default to using token)
- The editor is now using the embedded IDE. The embedding functionalities got some improves as well.
- You can share your snippet using a permanent URL: http://dev--wenyan-snippets.netlify.com/snippet/12
- Mobile friendly, sort of
- Benefit from the global token, you can see the snippets that you have access to.

image

Further works
- Fork
- Tooltips for Icons
- Publish to snippets for IDE
- Comments
- Vote inside of snippet view

There is a bug for autoloading the snippets when the screen is too large (not scrollbar), I will fix it soon. If you encounter is, please resize your browser until it becomes scrollable XP

**Comment by LingDong-** [comment]
👍 Very nice job! 

Aside from the awesome improvements, I also noticed some glitches/UI nuisances, I'm just blurting them out here as a reference. Feel free to address them or leave them for the future. I can also look into them in the latter case. Let me know what you think :D

### Bugs/glitches:

- After attempting to edit user name and hitting cancel, the username disappears from the top bar.
Scrolling doesn’t work on either desktop Safari or mobile Safari, regardless of window size. If you couldn’t reproduce the problem, I can look into it.
- The “cloud upload” button keeps flickering when typing
- Pressing `+` button when an untitled file is open doesn’t work, with console error message `Navigating to current location ("/new") is not allowed`. If there is a logical/technical issue that prevents this from working, maybe we can hide the `+` button. This also happens after searching for `is:me`.
- Fork button works weirdly. On safari it doesn’t work at all `/new is not allowed`. On Chrome it does fork, but it happens in the background and the small window doesn’t go away, kinda confusing. I’m wondering now that username and token are global, we can make forking implicit. - When you try to edit something that’s yours, you get to edit it. When you try to edit someone else’s locked snippet, it automatically produces a fork.
- Perhaps we should even remove the `public` option, being able to edit someone else’s stuff is weird anyways.

### Potential UI improvements:

In maxified editing mode:

- When hovering above filename and username, the cursor should change to `cursor:text` and a very light background shade/subtle outline can show up behind the text, to show the text is editable
- It seems that the only way to exit editing (aside from browser “back” button) is to click on the 文言片語 title (and that title doesn’t have a visual affordance for clicking). Perhaps a `<` back button would be nice?
- The globe/lock button suffers from what I call video player button dilemma. Does clicking on the lock icon make the file locked, or does it indicate the file is currently locked? I think perhaps a tooltip for hovering might be helpful to users.

Generally:

- Perhaps the thumbs up/down buttons can be slightly smaller. I used -1/+1 because the thumbs up/down buttons look too thick, that they look like prominent elements on the page. The site is not hosting entertainment/forum/social stuff where thumbs up/down are really important things to do. Wonder if there are prettier and less obtrusive icons.
- The title text 文言片語 could use just a tiny bit of left shifting to keep flush with the left edge of the content.
- If I have an unsaved document, then whenever I try to create a new file, it keeps nagging me “Unsaved draft load it blah blah”. Perhaps this should happen only once, and when the user clicks cancel, then the unsaved draft is trashed forever. Could say “Clicking cancel will discard the draft” in the alert message.
- Maybe we can somehow encourage the user to save their token elsewhere, so they don’t suddenly lose access when they switch computers/browsers/empty cache. Perhaps a line of tiny text of advice in the user profile popup.

**Comment by antfu** [comment]
Thanks for all the detailed testing and review! Sorry, I was just wanting you to have an overview look since it's still working in progress (maybe I should call you later  😂). But very much appreciated! All your points sound great and happy to make the fix/adjust. I will edit your comment as a checklist to show the progress.

> When you try to edit someone else’s locked snippet, it automatically produces a fork.

Sounds a little bit wired, do we need that many forks? Or maybe we could raise a prompt to fork when user trying to change the code?

> Perhaps we should even remove the public option, being able to edit someone else’s stuff is weird anyway.

Agreed. One concern is that the username is currently optional, you can even use the same name as the other, which may bring confusion. One solution is that we bring up the user system, but somehow that will kinda change the current architecture. What do you think about it?

Thanks!

**Comment by antfu** [comment]
For the voting icon, how about this?
image

**Comment by LingDong-** [comment]
The new voting icons are very neat!

I agree that the user system might be too complex for the current stage, maybe simply this:
when you're trying to edit something, if it yours, then you simply get to edit it; If it's locked by someone else, It pops up a dialog with two options: fork/cancel. If it's public, it pops up dialog with three options: fork/edit/cancel. How does that sound?

I'm totally happy to test things out.

**Comment by antfu** [comment]
Ok. I think I have finished most of the problems/improvements you listed. Let me know if there is anything could be done better.

- The `back` button is not in a good position for wider screens. I will try another method to make it looks good on both situation
- It's no longer possible to publish a `public` snippet. The existing `public` snippets still work.
- A comment system is added, powered by [disqus](https://disqus.com/home/forums/wenyan-snippets/). If you would like to have an account, I can invite you to be the mod :)
- The comment counting display will be support soon.
- When you edit the snippets that you don't have access to it, a prompt will appear asking you to fork it or enter the token of the snippet(if you know) to modify.
- I am thinking to store the "temporary token" of a snippet to local storage. Which adds flexibility to control access.

**Comment by LingDong-** [comment]
Thanks, awesome work 👍

The new features/fixes all looks great! I was just about to say everything's perfect, but finally I found some tiny glitches :D

- Full screen editor doesn't show up under this particular sequence of actions: First search for something, e.g. `hello` in the search box, then, click play button on one of the snippets, then, click "fullscreen" on the top bar of the windowed editor, yet fullscreen doesn't show up. The URL in the address bar is correct, if I do refresh then the fullscreen editor shows up correctly, wondering if all we need is to trigger the refresh.

- When moving over the globe/lock icon indicating public/private in the grid view, the cursor turns into pointer, but clicking on the icons doesn't seem to do anything.

- Not sure if it's just my browser, but the editor resize doesn't get triggered often/fast enough, so when resizing the window quickly I get this:

image

The white margin stays and doesn't go away even when I'm finished with resizing.

> The back button is not in a good position for wider screens.

Agreed

> A comment system is added, powered by disqus. If you would like to have an account, I can invite you to be the mod

Pretty cool! Currently there is nothing that needs to be modded, so let me procrastinate on that one :)

> store the "temporary token" of a snippet to local storage

Sounds great.

**Comment by antfu** [comment]
All the problems should be fixed :) Please check them out.

> store the "temporary token" of a snippet to local storage

I will treat this as an enhancement and would make it in another PR.

**Comment by LingDong-** [comment]
Perfect 🚀

**Comment by LingDong-** [comment]
Hmm... Just realized that it seems that this is not updating to snippet.wy-lang.org. I did clear cache and stuff, and triggered re-deploy on netlify, but to no avail...

Netlify seems to think it's deploying successfully. Wondering what the issue could be. 🤔

**Comment by antfu** [comment]
Just check it out and get no luck... Actually I have faced a similar issue when I was developing another project, I contacted the staff and they can see the up to date site, don't know why. And the problem got resolved in a few days without doing anything. So I guess it's probably some cache glitch of some services in the middle. Maybe we could wait and check out another day? :|

**Comment by LingDong-** [comment]
😂 Sure.

**Comment by antfu** [comment]
Damn. My fault. I forget that the deploy folder it's now `dist` not `static`. It should be fixed now.

**Pull request merged**
